In [1]:
import pandas as pd, sqlite3
 
sales = pd.read_csv("sales_week.csv"); sales["revenue"] = sales["qty"] * sales["price"]
fruits = pd.read_csv("fruits.csv")
 
conn = sqlite3.connect("stall.db")
sales.to_sql("sales", conn, if_exists="replace", index=False)
fruits.to_sql("fruits", conn, if_exists="replace", index=False)
 
def run(sql): return pd.read_sql(sql, conn)

In [2]:
run("""
    SELECT fruit, SUM(revenue) AS total_revenue
    FROM sales
    GROUP BY fruit
    ORDER BY total_revenue DESC
""")

    fruit  total_revenue
0   grape           6650
1   mango           5760
2  orange           3220
3   apple           2580
4   lemon           1200
5  banana            820

In [4]:
run("""
    SELECT fruit, SUM(revenue) AS total_revenue
    FROM sales
    GROUP BY fruit
    ORDER BY total_revenue DESC
""")

    fruit  total_revenue
0   grape           6650
1   mango           5760
2  orange           3220
3   apple           2580
4   lemon           1200
5  banana            820

In [5]:
run("""
    SELECT fruit, SUM(qty) AS total_quantity
    FROM sales
    GROUP BY fruit
    ORDER BY total_quantity DESC
""")

    fruit  total_quantity
0  orange             161
1   mango             144
2   grape             133
3   apple              86
4  banana              82
5   lemon              80

In [6]:
run("""
    SELECT stall, ROUND(AVG(revenue), 1) AS average_revenue
    FROM sales
    GROUP BY stall
""")

   stall  average_revenue
0  North            343.5
1  South            391.3

In [7]:
run("""
    SELECT category, MAX(revenue) AS max_revenue
    FROM sales
    GROUP BY category
    ORDER BY max_revenue DESC
""")

   category  max_revenue
0     berry         1150
1  tropical         1000
2      pome          630
3    citrus          420

In [9]:
run("SELECT fruit, COUNT(*) AS sales_count FROM sales GROUP BY fruit")

    fruit  sales_count
0   apple            6
1  banana            6
2   grape           11
3   lemon            8
4   mango           11
5  orange           13

In [10]:
run("SELECT stall, COUNT(DISTINCT fruit) AS kinds FROM sales GROUP BY stall")

   stall  kinds
0  North      6
1  South      6

In [11]:
run("""
    SELECT stall, COUNT(*) AS sales_count
    FROM sales
    GROUP BY stall
""")

   stall  sales_count
0  North           27
1  South           28

In [12]:
run("""
    SELECT category, COUNT(DISTINCT fruit) AS distinct_fruits
    FROM sales
    GROUP BY category
""")

   category  distinct_fruits
0     berry                1
1    citrus                2
2      pome                1
3  tropical                2

In [13]:
#3

In [14]:
run("""
    SELECT fruit, SUM(revenue) AS total
    FROM sales
    GROUP BY fruit
    HAVING SUM(revenue) > 3000
""")

    fruit  total
0   grape   6650
1   mango   5760
2  orange   3220

In [15]:
run("""
    SELECT fruit, SUM(revenue) AS total_revenue
    FROM sales
    GROUP BY fruit
    HAVING SUM(revenue) > 3000
""")

    fruit  total_revenue
0   grape           6650
1   mango           5760
2  orange           3220

In [16]:
run("""
    SELECT fruit, COUNT(*) AS sales_count
    FROM sales
    GROUP BY fruit
    HAVING COUNT(*) > 8
""")

    fruit  sales_count
0   grape           11
1   mango           11
2  orange           13

In [17]:
run("""
    SELECT fruit, SUM(revenue) AS total_revenue
    FROM sales
    WHERE price >= 20
    GROUP BY fruit
    HAVING SUM(revenue) > 2000
""")

    fruit  total_revenue
0   apple           2580
1   grape           6650
2   mango           5760
3  orange           3220

In [18]:
#4

In [19]:
run("""
    SELECT fruit, SUM(revenue) AS total
    FROM sales
    GROUP BY fruit
    ORDER BY total DESC
    LIMIT 1
""")

   fruit  total
0  grape   6650

In [20]:
run("""
    SELECT category, SUM(revenue) AS total_revenue
    FROM sales
    GROUP BY category
    ORDER BY total_revenue DESC
    LIMIT 1
""")

  category  total_revenue
0    berry           6650

In [21]:
run("""
    SELECT fruit, COUNT(*) AS sales_count
    FROM sales
    GROUP BY fruit
    ORDER BY sales_count ASC
    LIMIT 3
""")

    fruit  sales_count
0   apple            6
1  banana            6
2   lemon            8

In [22]:
#5

In [23]:
run("""
    SELECT s.fruit, s.revenue, f.supplier, f.cost_price
    FROM sales AS s
    JOIN fruits AS f
    ON s.fruit = f.fruit
""")

     fruit  revenue    supplier  cost_price
0    mango      160  TropicoLtd          25
1   orange      360    CitrusCo          12
2    grape      300   VineyardX          32
3   orange      400    CitrusCo          12
4    grape      700   VineyardX          32
5    apple      450  FreshFarms          18
6   banana      120  TropicoLtd           6
7    mango      280  TropicoLtd          25
8    grape      200   VineyardX          32
9    grape     1000   VineyardX          32
10  orange      360    CitrusCo          12
11   apple       90  FreshFarms          18
12   mango      120  TropicoLtd          25
13   grape      250   VineyardX          32
14  orange      380    CitrusCo          12
15   apple      540  FreshFarms          18
16   grape     1050   VineyardX          32
17   mango      240  TropicoLtd          25
18  banana      130  TropicoLtd           6
19  orange      100    CitrusCo          12
20  orange      420    CitrusCo          12
21   apple      510  FreshFarms          18
22   mango      720  TropicoLtd          25
23   grape      200   VineyardX          32
24   mango      440  TropicoLtd          25
25   grape     1150   VineyardX          32
26  orange      160    CitrusCo          12
27   mango      840  TropicoLtd          25
28  orange       40    CitrusCo          12
29   apple      630  FreshFarms          18
30  banana      150  TropicoLtd           6
31  orange      100    CitrusCo          12
32   mango      280  TropicoLtd          25
33   grape      200   VineyardX          32
34   mango      680  TropicoLtd          25
35  orange      300    CitrusCo          12
36   grape      750   VineyardX          32
37  banana      100  TropicoLtd           6
38  orange      240    CitrusCo          12
39   mango     1000  TropicoLtd          25
40  orange      140    CitrusCo          12
41  banana      210  TropicoLtd           6
42   mango     1000  TropicoLtd          25
43   grape      850   VineyardX          32
44  orange      220    CitrusCo          12
45  banana      110  TropicoLtd           6
46   apple      360  FreshFarms          18

In [24]:
run("""
    SELECT s.fruit, s.revenue, f.supplier, f.cost_price
    FROM sales AS s
    JOIN fruits AS f
    ON s.fruit = f.fruit
""")

     fruit  revenue    supplier  cost_price
0    mango      160  TropicoLtd          25
1   orange      360    CitrusCo          12
2    grape      300   VineyardX          32
3   orange      400    CitrusCo          12
4    grape      700   VineyardX          32
5    apple      450  FreshFarms          18
6   banana      120  TropicoLtd           6
7    mango      280  TropicoLtd          25
8    grape      200   VineyardX          32
9    grape     1000   VineyardX          32
10  orange      360    CitrusCo          12
11   apple       90  FreshFarms          18
12   mango      120  TropicoLtd          25
13   grape      250   VineyardX          32
14  orange      380    CitrusCo          12
15   apple      540  FreshFarms          18
16   grape     1050   VineyardX          32
17   mango      240  TropicoLtd          25
18  banana      130  TropicoLtd           6
19  orange      100    CitrusCo          12
20  orange      420    CitrusCo          12
21   apple      510  FreshFarms          18
22   mango      720  TropicoLtd          25
23   grape      200   VineyardX          32
24   mango      440  TropicoLtd          25
25   grape     1150   VineyardX          32
26  orange      160    CitrusCo          12
27   mango      840  TropicoLtd          25
28  orange       40    CitrusCo          12
29   apple      630  FreshFarms          18
30  banana      150  TropicoLtd           6
31  orange      100    CitrusCo          12
32   mango      280  TropicoLtd          25
33   grape      200   VineyardX          32
34   mango      680  TropicoLtd          25
35  orange      300    CitrusCo          12
36   grape      750   VineyardX          32
37  banana      100  TropicoLtd           6
38  orange      240    CitrusCo          12
39   mango     1000  TropicoLtd          25
40  orange      140    CitrusCo          12
41  banana      210  TropicoLtd           6
42   mango     1000  TropicoLtd          25
43   grape      850   VineyardX          32
44  orange      220    CitrusCo          12
45  banana      110  TropicoLtd           6
46   apple      360  FreshFarms          18

In [25]:
run("""
    SELECT s.fruit,
           s.revenue,
           f.cost_price,
           s.revenue - (s.qty * f.cost_price) AS profit
    FROM sales AS s
    JOIN fruits AS f
    ON s.fruit = f.fruit
""")

     fruit  revenue  cost_price  profit
0    mango      160          25      60
1   orange      360          12     144
2    grape      300          32     108
3   orange      400          12     160
4    grape      700          32     252
5    apple      450          18     180
6   banana      120           6      48
7    mango      280          25     105
8    grape      200          32      72
9    grape     1000          32     360
10  orange      360          12     144
11   apple       90          18      36
12   mango      120          25      45
13   grape      250          32      90
14  orange      380          12     152
15   apple      540          18     216
16   grape     1050          32     378
17   mango      240          25      90
18  banana      130           6      52
19  orange      100          12      40
20  orange      420          12     168
21   apple      510          18     204
22   mango      720          25     270
23   grape      200          32      72
24   mango      440          25     165
25   grape     1150          32     414
26  orange      160          12      64
27   mango      840          25     315
28  orange       40          12      16
29   apple      630          18     252
30  banana      150           6      60
31  orange      100          12      40
32   mango      280          25     105
33   grape      200          32      72
34   mango      680          25     255
35  orange      300          12     120
36   grape      750          32     270
37  banana      100           6      40
38  orange      240          12      96
39   mango     1000          25     375
40  orange      140          12      56
41  banana      210           6      84
42   mango     1000          25     375
43   grape      850          32     306
44  orange      220          12      88
45  banana      110           6      44
46   apple      360          18     144

In [26]:
run("""
    SELECT s.fruit,
           s.revenue,
           f.supplier,
           f.origin
    FROM sales AS s
    JOIN fruits AS f
    ON s.fruit = f.fruit
    WHERE f.origin = 'imported'
""")

     fruit  revenue    supplier    origin
0   banana      100  TropicoLtd  imported
1   banana      110  TropicoLtd  imported
2   banana      120  TropicoLtd  imported
3   banana      130  TropicoLtd  imported
4   banana      150  TropicoLtd  imported
5   banana      210  TropicoLtd  imported
6    mango      120  TropicoLtd  imported
7    mango      160  TropicoLtd  imported
8    mango      240  TropicoLtd  imported
9    mango      280  TropicoLtd  imported
10   mango      280  TropicoLtd  imported
11   mango      440  TropicoLtd  imported
12   mango      680  TropicoLtd  imported
13   mango      720  TropicoLtd  imported
14   mango      840  TropicoLtd  imported
15   mango     1000  TropicoLtd  imported
16   mango     1000  TropicoLtd  imported
17   grape      200   VineyardX  imported
18   grape      200   VineyardX  imported
19   grape      200   VineyardX  imported
20   grape      250   VineyardX  imported
21   grape      300   VineyardX  imported
22   grape      700   VineyardX  imported
23   grape      750   VineyardX  imported
24   grape      850   VineyardX  imported
25   grape     1000   VineyardX  imported
26   grape     1050   VineyardX  imported
27   grape     1150   VineyardX  imported

In [27]:
#6
run("""
    SELECT s.fruit, s.revenue, f.supplier
    FROM sales AS s
    LEFT JOIN fruits AS f
    ON s.fruit = f.fruit
""")

     fruit  revenue    supplier
0    mango      160  TropicoLtd
1   orange      360    CitrusCo
2    grape      300   VineyardX
3   orange      400    CitrusCo
4    grape      700   VineyardX
5    lemon       75        None
6    apple      450  FreshFarms
7    lemon      180        None
8   banana      120  TropicoLtd
9    mango      280  TropicoLtd
10   grape      200   VineyardX
11   grape     1000   VineyardX
12  orange      360    CitrusCo
13   lemon      150        None
14   apple       90  FreshFarms
15   mango      120  TropicoLtd
16   lemon      225        None
17   grape      250   VineyardX
18  orange      380    CitrusCo
19   apple      540  FreshFarms
20   grape     1050   VineyardX
21   mango      240  TropicoLtd
22  banana      130  TropicoLtd
23  orange      100    CitrusCo
24   lemon      270        None
25  orange      420    CitrusCo
26   apple      510  FreshFarms
27   mango      720  TropicoLtd
28   grape      200   VineyardX
29   mango      440  TropicoLtd
30   grape     1150   VineyardX
31  orange      160    CitrusCo
32   mango      840  TropicoLtd
33  orange       40    CitrusCo
34   apple      630  FreshFarms
35  banana      150  TropicoLtd
36   lemon       30        None
37  orange      100    CitrusCo
38   mango      280  TropicoLtd
39   grape      200   VineyardX
40   lemon      225        None
41   mango      680  TropicoLtd
42  orange      300    CitrusCo
43   grape      750   VineyardX
44  banana      100  TropicoLtd
45  orange      240    CitrusCo
46   mango     1000  TropicoLtd
47  orange      140    CitrusCo
48  banana      210  TropicoLtd
49   lemon       45        None
50   mango     1000  TropicoLtd
51   grape      850   VineyardX
52  orange      220    CitrusCo
53  banana      110  TropicoLtd
54   apple      360  FreshFarms

In [28]:
run("""
    SELECT s.fruit,
           s.revenue,
           f.supplier
    FROM sales AS s
    LEFT JOIN fruits AS f
    ON s.fruit = f.fruit
""")

     fruit  revenue    supplier
0    mango      160  TropicoLtd
1   orange      360    CitrusCo
2    grape      300   VineyardX
3   orange      400    CitrusCo
4    grape      700   VineyardX
5    lemon       75        None
6    apple      450  FreshFarms
7    lemon      180        None
8   banana      120  TropicoLtd
9    mango      280  TropicoLtd
10   grape      200   VineyardX
11   grape     1000   VineyardX
12  orange      360    CitrusCo
13   lemon      150        None
14   apple       90  FreshFarms
15   mango      120  TropicoLtd
16   lemon      225        None
17   grape      250   VineyardX
18  orange      380    CitrusCo
19   apple      540  FreshFarms
20   grape     1050   VineyardX
21   mango      240  TropicoLtd
22  banana      130  TropicoLtd
23  orange      100    CitrusCo
24   lemon      270        None
25  orange      420    CitrusCo
26   apple      510  FreshFarms
27   mango      720  TropicoLtd
28   grape      200   VineyardX
29   mango      440  TropicoLtd
30   grape     1150   VineyardX
31  orange      160    CitrusCo
32   mango      840  TropicoLtd
33  orange       40    CitrusCo
34   apple      630  FreshFarms
35  banana      150  TropicoLtd
36   lemon       30        None
37  orange      100    CitrusCo
38   mango      280  TropicoLtd
39   grape      200   VineyardX
40   lemon      225        None
41   mango      680  TropicoLtd
42  orange      300    CitrusCo
43   grape      750   VineyardX
44  banana      100  TropicoLtd
45  orange      240    CitrusCo
46   mango     1000  TropicoLtd
47  orange      140    CitrusCo
48  banana      210  TropicoLtd
49   lemon       45        None
50   mango     1000  TropicoLtd
51   grape      850   VineyardX
52  orange      220    CitrusCo
53  banana      110  TropicoLtd
54   apple      360  FreshFarms

In [29]:
run("""
    SELECT s.fruit,
           s.revenue,
           f.supplier
    FROM sales AS s
    LEFT JOIN fruits AS f
    ON s.fruit = f.fruit
    WHERE f.supplier IS NULL
""")

   fruit  revenue supplier
0  lemon       75     None
1  lemon      180     None
2  lemon      150     None
3  lemon      225     None
4  lemon      270     None
5  lemon       30     None
6  lemon      225     None
7  lemon       45     None

In [30]:
#7
run("""
    SELECT f.supplier,
           SUM(s.revenue - s.qty * f.cost_price) AS profit
    FROM sales AS s
    JOIN fruits AS f
    ON s.fruit = f.fruit
    GROUP BY f.supplier
    ORDER BY profit DESC
""")

     supplier  profit
0  TropicoLtd    2488
1   VineyardX    2394
2    CitrusCo    1288
3  FreshFarms    1032

In [31]:
run("""
    SELECT f.supplier,
           SUM(s.revenue - s.qty * f.cost_price) AS total_profit
    FROM sales AS s
    JOIN fruits AS f
    ON s.fruit = f.fruit
    GROUP BY f.supplier
    ORDER BY total_profit DESC
""")

     supplier  total_profit
0  TropicoLtd          2488
1   VineyardX          2394
2    CitrusCo          1288
3  FreshFarms          1032

In [32]:
run("""
    SELECT f.origin,
           SUM(s.revenue) AS total_revenue
    FROM sales AS s
    JOIN fruits AS f
    ON s.fruit = f.fruit
    GROUP BY f.origin
""")

     origin  total_revenue
0  imported          13230
1     local           5800

In [33]:
run("""
    SELECT f.supplier,
           AVG(s.revenue - s.qty * f.cost_price) AS average_profit
    FROM sales AS s
    JOIN fruits AS f
    ON s.fruit = f.fruit
    GROUP BY f.supplier
    ORDER BY average_profit DESC
""")

     supplier  average_profit
0   VineyardX      217.636364
1  FreshFarms      172.000000
2  TropicoLtd      146.352941
3    CitrusCo       99.076923

In [34]:
run("""
    SELECT f.supplier,
           AVG(s.revenue - s.qty * f.cost_price) AS average_profit
    FROM sales AS s
    JOIN fruits AS f
    ON s.fruit = f.fruit
    GROUP BY f.supplier
    ORDER BY average_profit DESC
""")

     supplier  average_profit
0   VineyardX      217.636364
1  FreshFarms      172.000000
2  TropicoLtd      146.352941
3    CitrusCo       99.076923

In [35]:
#eod

In [37]:
run("""
    SELECT fruit,
           SUM(revenue) AS total_revenue,
           COUNT(*) AS sales_count
    FROM sales
    GROUP BY fruit
    ORDER BY total_revenue DESC
""")

    fruit  total_revenue  sales_count
0   grape           6650           11
1   mango           5760           11
2  orange           3220           13
3   apple           2580            6
4   lemon           1200            8
5  banana            820            6

In [38]:
run("""
    SELECT stall,
           ROUND(AVG(revenue), 1) AS average_sale_value
    FROM sales
    GROUP BY stall
""")

   stall  average_sale_value
0  North               343.5
1  South               391.3

In [39]:
run("""
    SELECT fruit,
           SUM(revenue) AS total_revenue
    FROM sales
    GROUP BY fruit
    HAVING SUM(revenue) > 3000
    ORDER BY total_revenue DESC
""")

    fruit  total_revenue
0   grape           6650
1   mango           5760
2  orange           3220

In [40]:
run("""
    SELECT category,
           SUM(revenue) AS total_revenue
    FROM sales
    GROUP BY category
    ORDER BY total_revenue DESC
    LIMIT 1
""")

  category  total_revenue
0    berry           6650

In [41]:
run("""
    SELECT f.supplier,
           SUM(s.revenue - s.qty * f.cost_price) AS total_profit
    FROM sales AS s
    JOIN fruits AS f
    ON s.fruit = f.fruit
    GROUP BY f.supplier
    ORDER BY total_profit DESC
""")

     supplier  total_profit
0  TropicoLtd          2488
1   VineyardX          2394
2    CitrusCo          1288
3  FreshFarms          1032

In [42]:
run("""
    SELECT f.origin,
           SUM(s.revenue - s.qty * f.cost_price) AS total_profit
    FROM sales AS s
    JOIN fruits AS f
    ON s.fruit = f.fruit
    GROUP BY f.origin
    ORDER BY total_profit DESC
""")

     origin  total_profit
0  imported          4882
1     local          2320

In [43]:
run("""
    SELECT s.fruit,
           s.revenue,
           f.supplier
    FROM sales AS s
    LEFT JOIN fruits AS f
    ON s.fruit = f.fruit
    WHERE f.supplier IS NULL
""")

   fruit  revenue supplier
0  lemon       75     None
1  lemon      180     None
2  lemon      150     None
3  lemon      225     None
4  lemon      270     None
5  lemon       30     None
6  lemon      225     None
7  lemon       45     None

In [44]:
run("""
    SELECT stall,
           fruit,
           SUM(revenue) AS total_revenue
    FROM sales
    GROUP BY stall, fruit
    ORDER BY stall, total_revenue DESC
""")

    stall   fruit  total_revenue
0   North   mango           2800
1   North   apple           2130
2   North   grape           1700
3   North  orange           1640
4   North   lemon            675
5   North  banana            330
6   South   grape           4950
7   South   mango           2960
8   South  orange           1580
9   South   lemon            525
10  South  banana            490
11  South   apple            450

In [52]:
run("""
    SELECT f.supplier,
           SUM(s.revenue - s.qty * f.cost_price) AS total_profit
    FROM sales AS s
    JOIN fruits AS f
    ON s.fruit = f.fruit
    GROUP BY f.supplier
    HAVING SUM(s.revenue - s.qty * f.cost_price) > 2000
    ORDER BY total_profit DESC
""")

     supplier  total_profit
0  TropicoLtd          2488
1   VineyardX          2394

In [55]:
conn.executescript("""
DROP TABLE IF EXISTS suppliers;

CREATE TABLE suppliers (
    supplier TEXT,
    city TEXT
);

INSERT INTO suppliers VALUES
('FreshFarms','Chennai'),
('TropicoLtd','Mumbai'),
('CitrusCo','Nagpur'),
('VineyardX','Nashik');
""")

In [50]:
run("""
SELECT
    s.fruit,
    s.revenue,
    f.supplier,
    sp.city
FROM sales AS s
JOIN fruits AS f
ON s.fruit = f.fruit
JOIN suppliers AS sp
ON f.supplier = sp.supplier;
""")

Empty DataFrame
Columns: [fruit, revenue, supplier, city]
Index: []

In [56]:
run("""
    SELECT s.fruit,
           s.revenue,
           f.supplier,
           sp.city
    FROM sales AS s
    JOIN fruits AS f
    ON s.fruit = f.fruit
    JOIN suppliers AS sp
    ON f.supplier = sp.supplier
""")

     fruit  revenue    supplier     city
0    mango      160  TropicoLtd   Mumbai
1   orange      360    CitrusCo   Nagpur
2    grape      300   VineyardX   Nashik
3   orange      400    CitrusCo   Nagpur
4    grape      700   VineyardX   Nashik
5    apple      450  FreshFarms  Chennai
6   banana      120  TropicoLtd   Mumbai
7    mango      280  TropicoLtd   Mumbai
8    grape      200   VineyardX   Nashik
9    grape     1000   VineyardX   Nashik
10  orange      360    CitrusCo   Nagpur
11   apple       90  FreshFarms  Chennai
12   mango      120  TropicoLtd   Mumbai
13   grape      250   VineyardX   Nashik
14  orange      380    CitrusCo   Nagpur
15   apple      540  FreshFarms  Chennai
16   grape     1050   VineyardX   Nashik
17   mango      240  TropicoLtd   Mumbai
18  banana      130  TropicoLtd   Mumbai
19  orange      100    CitrusCo   Nagpur
20  orange      420    CitrusCo   Nagpur
21   apple      510  FreshFarms  Chennai
22   mango      720  TropicoLtd   Mumbai
23   grape      200   VineyardX   Nashik
24   mango      440  TropicoLtd   Mumbai
25   grape     1150   VineyardX   Nashik
26  orange      160    CitrusCo   Nagpur
27   mango      840  TropicoLtd   Mumbai
28  orange       40    CitrusCo   Nagpur
29   apple      630  FreshFarms  Chennai
30  banana      150  TropicoLtd   Mumbai
31  orange      100    CitrusCo   Nagpur
32   mango      280  TropicoLtd   Mumbai
33   grape      200   VineyardX   Nashik
34   mango      680  TropicoLtd   Mumbai
35  orange      300    CitrusCo   Nagpur
36   grape      750   VineyardX   Nashik
37  banana      100  TropicoLtd   Mumbai
38  orange      240    CitrusCo   Nagpur
39   mango     1000  TropicoLtd   Mumbai
40  orange      140    CitrusCo   Nagpur
41  banana      210  TropicoLtd   Mumbai
42   mango     1000  TropicoLtd   Mumbai
43   grape      850   VineyardX   Nashik
44  orange      220    CitrusCo   Nagpur
45  banana      110  TropicoLtd   Mumbai
46   apple      360  FreshFarms  Chennai

In [57]:
run("""
    SELECT
        SUM(CASE
                WHEN price >= 40 THEN revenue
                ELSE 0
            END) AS premium_revenue,
        SUM(CASE
                WHEN price < 40 THEN revenue
                ELSE 0
            END) AS regular_revenue
    FROM sales
""")

   premium_revenue  regular_revenue
0            12410             7820