In [1]:
import pandas as pd
import sqlite3
 
sales = pd.read_csv("sales_week.csv")
sales["revenue"] = sales["qty"] * sales["price"]
 
conn = sqlite3.connect("stall.db")            # a database file
sales.to_sql("sales", conn, if_exists="replace", index=False)

55

In [2]:
def run(sql):
    return pd.read_sql(sql, conn)
 
run("SELECT * FROM sales LIMIT 5")

         date  stall   fruit  category  qty  price  revenue
0  2024-06-03  North   mango  tropical    4     40      160
1  2024-06-03  North  orange    citrus   18     20      360
2  2024-06-03  North   grape     berry    6     50      300
3  2024-06-03  South  orange    citrus   20     20      400
4  2024-06-03  South   grape     berry   14     50      700

In [7]:
run("SELECT fruit, price FROM sales")
run("SELECT * FROM sales")

          date  stall   fruit  category  qty  price  revenue
0   2024-06-03  North   mango  tropical    4     40      160
1   2024-06-03  North  orange    citrus   18     20      360
2   2024-06-03  North   grape     berry    6     50      300
3   2024-06-03  South  orange    citrus   20     20      400
4   2024-06-03  South   grape     berry   14     50      700
5   2024-06-03  South   lemon    citrus    5     15       75
6   2024-06-04  North   apple      pome   15     30      450
7   2024-06-04  North   lemon    citrus   12     15      180
8   2024-06-04  North  banana  tropical   12     10      120
9   2024-06-04  North   mango  tropical    7     40      280
10  2024-06-04  North   grape     berry    4     50      200
11  2024-06-04  South   grape     berry   20     50     1000
12  2024-06-04  South  orange    citrus   18     20      360
13  2024-06-04  South   lemon    citrus   10     15      150
14  2024-06-04  South   apple      pome    3     30       90
15  2024-06-05  North   mango  tropical    3     40      120
16  2024-06-05  North   lemon    citrus   15     15      225
17  2024-06-05  North   grape     berry    5     50      250
18  2024-06-05  North  orange    citrus   19     20      380
19  2024-06-05  North   apple      pome   18     30      540
20  2024-06-05  South   grape     berry   21     50     1050
21  2024-06-05  South   mango  tropical    6     40      240
22  2024-06-05  South  banana  tropical   13     10      130
23  2024-06-05  South  orange    citrus    5     20      100
24  2024-06-05  South   lemon    citrus   18     15      270
25  2024-06-06  North  orange    citrus   21     20      420
26  2024-06-06  North   apple      pome   17     30      510
27  2024-06-06  North   mango  tropical   18     40      720
28  2024-06-06  North   grape     berry    4     50      200
29  2024-06-06  South   mango  tropical   11     40      440
30  2024-06-06  South   grape     berry   23     50     1150
31  2024-06-06  South  orange    citrus    8     20      160
32  2024-06-07  North   mango  tropical   21     40      840
33  2024-06-07  North  orange    citrus    2     20       40
34  2024-06-07  North   apple      pome   21     30      630
35  2024-06-07  South  banana  tropical   15     10      150
36  2024-06-07  South   lemon    citrus    2     15       30
37  2024-06-07  South  orange    citrus    5     20      100
38  2024-06-07  South   mango  tropical    7     40      280
39  2024-06-07  South   grape     berry    4     50      200
40  2024-06-08  North   lemon    citrus   15     15      225
41  2024-06-08  North   mango  tropical   17     40      680
42  2024-06-08  North  orange    citrus   15     20      300
43  2024-06-08  North   grape     berry   15     50      750
44  2024-06-08  South  banana  tropical   10     10      100
45  2024-06-08  South  orange    citrus   12     20      240
46  2024-06-08  South   mango  tropical   25     40     1000
47  2024-06-09  North  orange    citrus    7     20      140
48  2024-06-09  North  banana  tropical   21     10      210
49  2024-06-09  North   lemon    citrus    3     15       45
50  2024-06-09  South   mango  tropical   25     40     1000
51  2024-06-09  South   grape     berry   17     50      850
52  2024-06-09  South  orange    citrus   11     20      220
53  2024-06-09  South  banana  tropical   11     10      110
54  2024-06-09  South   apple      pome   12     30      360

In [4]:
run("SELECT fruit, qty, revenue FROM sales")

     fruit  qty  revenue
0    mango    4      160
1   orange   18      360
2    grape    6      300
3   orange   20      400
4    grape   14      700
5    lemon    5       75
6    apple   15      450
7    lemon   12      180
8   banana   12      120
9    mango    7      280
10   grape    4      200
11   grape   20     1000
12  orange   18      360
13   lemon   10      150
14   apple    3       90
15   mango    3      120
16   lemon   15      225
17   grape    5      250
18  orange   19      380
19   apple   18      540
20   grape   21     1050
21   mango    6      240
22  banana   13      130
23  orange    5      100
24   lemon   18      270
25  orange   21      420
26   apple   17      510
27   mango   18      720
28   grape    4      200
29   mango   11      440
30   grape   23     1150
31  orange    8      160
32   mango   21      840
33  orange    2       40
34   apple   21      630
35  banana   15      150
36   lemon    2       30
37  orange    5      100
38   mango    7      280
39   grape    4      200
40   lemon   15      225
41   mango   17      680
42  orange   15      300
43   grape   15      750
44  banana   10      100
45  orange   12      240
46   mango   25     1000
47  orange    7      140
48  banana   21      210
49   lemon    3       45
50   mango   25     1000
51   grape   17      850
52  orange   11      220
53  banana   11      110
54   apple   12      360

In [5]:
run("SELECT * FROM sales")

          date  stall   fruit  category  qty  price  revenue
0   2024-06-03  North   mango  tropical    4     40      160
1   2024-06-03  North  orange    citrus   18     20      360
2   2024-06-03  North   grape     berry    6     50      300
3   2024-06-03  South  orange    citrus   20     20      400
4   2024-06-03  South   grape     berry   14     50      700
5   2024-06-03  South   lemon    citrus    5     15       75
6   2024-06-04  North   apple      pome   15     30      450
7   2024-06-04  North   lemon    citrus   12     15      180
8   2024-06-04  North  banana  tropical   12     10      120
9   2024-06-04  North   mango  tropical    7     40      280
10  2024-06-04  North   grape     berry    4     50      200
11  2024-06-04  South   grape     berry   20     50     1000
12  2024-06-04  South  orange    citrus   18     20      360
13  2024-06-04  South   lemon    citrus   10     15      150
14  2024-06-04  South   apple      pome    3     30       90
15  2024-06-05  North   mango  tropical    3     40      120
16  2024-06-05  North   lemon    citrus   15     15      225
17  2024-06-05  North   grape     berry    5     50      250
18  2024-06-05  North  orange    citrus   19     20      380
19  2024-06-05  North   apple      pome   18     30      540
20  2024-06-05  South   grape     berry   21     50     1050
21  2024-06-05  South   mango  tropical    6     40      240
22  2024-06-05  South  banana  tropical   13     10      130
23  2024-06-05  South  orange    citrus    5     20      100
24  2024-06-05  South   lemon    citrus   18     15      270
25  2024-06-06  North  orange    citrus   21     20      420
26  2024-06-06  North   apple      pome   17     30      510
27  2024-06-06  North   mango  tropical   18     40      720
28  2024-06-06  North   grape     berry    4     50      200
29  2024-06-06  South   mango  tropical   11     40      440
30  2024-06-06  South   grape     berry   23     50     1150
31  2024-06-06  South  orange    citrus    8     20      160
32  2024-06-07  North   mango  tropical   21     40      840
33  2024-06-07  North  orange    citrus    2     20       40
34  2024-06-07  North   apple      pome   21     30      630
35  2024-06-07  South  banana  tropical   15     10      150
36  2024-06-07  South   lemon    citrus    2     15       30
37  2024-06-07  South  orange    citrus    5     20      100
38  2024-06-07  South   mango  tropical    7     40      280
39  2024-06-07  South   grape     berry    4     50      200
40  2024-06-08  North   lemon    citrus   15     15      225
41  2024-06-08  North   mango  tropical   17     40      680
42  2024-06-08  North  orange    citrus   15     20      300
43  2024-06-08  North   grape     berry   15     50      750
44  2024-06-08  South  banana  tropical   10     10      100
45  2024-06-08  South  orange    citrus   12     20      240
46  2024-06-08  South   mango  tropical   25     40     1000
47  2024-06-09  North  orange    citrus    7     20      140
48  2024-06-09  North  banana  tropical   21     10      210
49  2024-06-09  North   lemon    citrus    3     15       45
50  2024-06-09  South   mango  tropical   25     40     1000
51  2024-06-09  South   grape     berry   17     50      850
52  2024-06-09  South  orange    citrus   11     20      220
53  2024-06-09  South  banana  tropical   11     10      110
54  2024-06-09  South   apple      pome   12     30      360

In [6]:
run("SELECT stall FROM sales")

    stall
0   North
1   North
2   North
3   South
4   South
5   South
6   North
7   North
8   North
9   North
10  North
11  South
12  South
13  South
14  South
15  North
16  North
17  North
18  North
19  North
20  South
21  South
22  South
23  South
24  South
25  North
26  North
27  North
28  North
29  South
30  South
31  South
32  North
33  North
34  North
35  South
36  South
37  South
38  South
39  South
40  North
41  North
42  North
43  North
44  South
45  South
46  South
47  North
48  North
49  North
50  South
51  South
52  South
53  South
54  South

In [10]:
run("SELECT * FROM sales WHERE price >= 40")

          date  stall  fruit  category  qty  price  revenue
0   2024-06-03  North  mango  tropical    4     40      160
1   2024-06-03  North  grape     berry    6     50      300
2   2024-06-03  South  grape     berry   14     50      700
3   2024-06-04  North  mango  tropical    7     40      280
4   2024-06-04  North  grape     berry    4     50      200
5   2024-06-04  South  grape     berry   20     50     1000
6   2024-06-05  North  mango  tropical    3     40      120
7   2024-06-05  North  grape     berry    5     50      250
8   2024-06-05  South  grape     berry   21     50     1050
9   2024-06-05  South  mango  tropical    6     40      240
10  2024-06-06  North  mango  tropical   18     40      720
11  2024-06-06  North  grape     berry    4     50      200
12  2024-06-06  South  mango  tropical   11     40      440
13  2024-06-06  South  grape     berry   23     50     1150
14  2024-06-07  North  mango  tropical   21     40      840
15  2024-06-07  South  mango  tropical    7     40      280
16  2024-06-07  South  grape     berry    4     50      200
17  2024-06-08  North  mango  tropical   17     40      680
18  2024-06-08  North  grape     berry   15     50      750
19  2024-06-08  South  mango  tropical   25     40     1000
20  2024-06-09  South  mango  tropical   25     40     1000
21  2024-06-09  South  grape     berry   17     50      850

In [11]:
run("SELECT * FROM sales WHERE fruit = 'apple'")

         date  stall  fruit category  qty  price  revenue
0  2024-06-04  North  apple     pome   15     30      450
1  2024-06-04  South  apple     pome    3     30       90
2  2024-06-05  North  apple     pome   18     30      540
3  2024-06-06  North  apple     pome   17     30      510
4  2024-06-07  North  apple     pome   21     30      630
5  2024-06-09  South  apple     pome   12     30      360

In [12]:
run("SELECT * FROM sales WHERE price >= 30 AND stall = 'North'")

          date  stall  fruit  category  qty  price  revenue
0   2024-06-03  North  mango  tropical    4     40      160
1   2024-06-03  North  grape     berry    6     50      300
2   2024-06-04  North  apple      pome   15     30      450
3   2024-06-04  North  mango  tropical    7     40      280
4   2024-06-04  North  grape     berry    4     50      200
5   2024-06-05  North  mango  tropical    3     40      120
6   2024-06-05  North  grape     berry    5     50      250
7   2024-06-05  North  apple      pome   18     30      540
8   2024-06-06  North  apple      pome   17     30      510
9   2024-06-06  North  mango  tropical   18     40      720
10  2024-06-06  North  grape     berry    4     50      200
11  2024-06-07  North  mango  tropical   21     40      840
12  2024-06-07  North  apple      pome   21     30      630
13  2024-06-08  North  mango  tropical   17     40      680
14  2024-06-08  North  grape     berry   15     50      750

In [13]:
run("SELECT * FROM sales WHERE fruit = 'banana'")

         date  stall   fruit  category  qty  price  revenue
0  2024-06-04  North  banana  tropical   12     10      120
1  2024-06-05  South  banana  tropical   13     10      130
2  2024-06-07  South  banana  tropical   15     10      150
3  2024-06-08  South  banana  tropical   10     10      100
4  2024-06-09  North  banana  tropical   21     10      210
5  2024-06-09  South  banana  tropical   11     10      110

In [14]:
run("SELECT * FROM sales WHERE qty > 15")

          date  stall   fruit  category  qty  price  revenue
0   2024-06-03  North  orange    citrus   18     20      360
1   2024-06-03  South  orange    citrus   20     20      400
2   2024-06-04  South   grape     berry   20     50     1000
3   2024-06-04  South  orange    citrus   18     20      360
4   2024-06-05  North  orange    citrus   19     20      380
5   2024-06-05  North   apple      pome   18     30      540
6   2024-06-05  South   grape     berry   21     50     1050
7   2024-06-05  South   lemon    citrus   18     15      270
8   2024-06-06  North  orange    citrus   21     20      420
9   2024-06-06  North   apple      pome   17     30      510
10  2024-06-06  North   mango  tropical   18     40      720
11  2024-06-06  South   grape     berry   23     50     1150
12  2024-06-07  North   mango  tropical   21     40      840
13  2024-06-07  North   apple      pome   21     30      630
14  2024-06-08  North   mango  tropical   17     40      680
15  2024-06-08  South   mango  tropical   25     40     1000
16  2024-06-09  North  banana  tropical   21     10      210
17  2024-06-09  South   mango  tropical   25     40     1000
18  2024-06-09  South   grape     berry   17     50      850

In [15]:
run("SELECT * FROM sales WHERE price >= 30 AND stall = 'South'")

          date  stall  fruit  category  qty  price  revenue
0   2024-06-03  South  grape     berry   14     50      700
1   2024-06-04  South  grape     berry   20     50     1000
2   2024-06-04  South  apple      pome    3     30       90
3   2024-06-05  South  grape     berry   21     50     1050
4   2024-06-05  South  mango  tropical    6     40      240
5   2024-06-06  South  mango  tropical   11     40      440
6   2024-06-06  South  grape     berry   23     50     1150
7   2024-06-07  South  mango  tropical    7     40      280
8   2024-06-07  South  grape     berry    4     50      200
9   2024-06-08  South  mango  tropical   25     40     1000
10  2024-06-09  South  mango  tropical   25     40     1000
11  2024-06-09  South  grape     berry   17     50      850
12  2024-06-09  South  apple      pome   12     30      360

In [16]:
run("SELECT * FROM sales WHERE fruit != 'apple'")

          date  stall   fruit  category  qty  price  revenue
0   2024-06-03  North   mango  tropical    4     40      160
1   2024-06-03  North  orange    citrus   18     20      360
2   2024-06-03  North   grape     berry    6     50      300
3   2024-06-03  South  orange    citrus   20     20      400
4   2024-06-03  South   grape     berry   14     50      700
5   2024-06-03  South   lemon    citrus    5     15       75
6   2024-06-04  North   lemon    citrus   12     15      180
7   2024-06-04  North  banana  tropical   12     10      120
8   2024-06-04  North   mango  tropical    7     40      280
9   2024-06-04  North   grape     berry    4     50      200
10  2024-06-04  South   grape     berry   20     50     1000
11  2024-06-04  South  orange    citrus   18     20      360
12  2024-06-04  South   lemon    citrus   10     15      150
13  2024-06-05  North   mango  tropical    3     40      120
14  2024-06-05  North   lemon    citrus   15     15      225
15  2024-06-05  North   grape     berry    5     50      250
16  2024-06-05  North  orange    citrus   19     20      380
17  2024-06-05  South   grape     berry   21     50     1050
18  2024-06-05  South   mango  tropical    6     40      240
19  2024-06-05  South  banana  tropical   13     10      130
20  2024-06-05  South  orange    citrus    5     20      100
21  2024-06-05  South   lemon    citrus   18     15      270
22  2024-06-06  North  orange    citrus   21     20      420
23  2024-06-06  North   mango  tropical   18     40      720
24  2024-06-06  North   grape     berry    4     50      200
25  2024-06-06  South   mango  tropical   11     40      440
26  2024-06-06  South   grape     berry   23     50     1150
27  2024-06-06  South  orange    citrus    8     20      160
28  2024-06-07  North   mango  tropical   21     40      840
29  2024-06-07  North  orange    citrus    2     20       40
30  2024-06-07  South  banana  tropical   15     10      150
31  2024-06-07  South   lemon    citrus    2     15       30
32  2024-06-07  South  orange    citrus    5     20      100
33  2024-06-07  South   mango  tropical    7     40      280
34  2024-06-07  South   grape     berry    4     50      200
35  2024-06-08  North   lemon    citrus   15     15      225
36  2024-06-08  North   mango  tropical   17     40      680
37  2024-06-08  North  orange    citrus   15     20      300
38  2024-06-08  North   grape     berry   15     50      750
39  2024-06-08  South  banana  tropical   10     10      100
40  2024-06-08  South  orange    citrus   12     20      240
41  2024-06-08  South   mango  tropical   25     40     1000
42  2024-06-09  North  orange    citrus    7     20      140
43  2024-06-09  North  banana  tropical   21     10      210
44  2024-06-09  North   lemon    citrus    3     15       45
45  2024-06-09  South   mango  tropical   25     40     1000
46  2024-06-09  South   grape     berry   17     50      850
47  2024-06-09  South  orange    citrus   11     20      220
48  2024-06-09  South  banana  tropical   11     10      110

In [17]:
#3
run("SELECT * FROM sales WHERE fruit IN ('apple', 'banana')")

          date  stall   fruit  category  qty  price  revenue
0   2024-06-04  North   apple      pome   15     30      450
1   2024-06-04  North  banana  tropical   12     10      120
2   2024-06-04  South   apple      pome    3     30       90
3   2024-06-05  North   apple      pome   18     30      540
4   2024-06-05  South  banana  tropical   13     10      130
5   2024-06-06  North   apple      pome   17     30      510
6   2024-06-07  North   apple      pome   21     30      630
7   2024-06-07  South  banana  tropical   15     10      150
8   2024-06-08  South  banana  tropical   10     10      100
9   2024-06-09  North  banana  tropical   21     10      210
10  2024-06-09  South  banana  tropical   11     10      110
11  2024-06-09  South   apple      pome   12     30      360

In [18]:
run("SELECT * FROM sales WHERE price BETWEEN 20 AND 40")

          date  stall   fruit  category  qty  price  revenue
0   2024-06-03  North   mango  tropical    4     40      160
1   2024-06-03  North  orange    citrus   18     20      360
2   2024-06-03  South  orange    citrus   20     20      400
3   2024-06-04  North   apple      pome   15     30      450
4   2024-06-04  North   mango  tropical    7     40      280
5   2024-06-04  South  orange    citrus   18     20      360
6   2024-06-04  South   apple      pome    3     30       90
7   2024-06-05  North   mango  tropical    3     40      120
8   2024-06-05  North  orange    citrus   19     20      380
9   2024-06-05  North   apple      pome   18     30      540
10  2024-06-05  South   mango  tropical    6     40      240
11  2024-06-05  South  orange    citrus    5     20      100
12  2024-06-06  North  orange    citrus   21     20      420
13  2024-06-06  North   apple      pome   17     30      510
14  2024-06-06  North   mango  tropical   18     40      720
15  2024-06-06  South   mango  tropical   11     40      440
16  2024-06-06  South  orange    citrus    8     20      160
17  2024-06-07  North   mango  tropical   21     40      840
18  2024-06-07  North  orange    citrus    2     20       40
19  2024-06-07  North   apple      pome   21     30      630
20  2024-06-07  South  orange    citrus    5     20      100
21  2024-06-07  South   mango  tropical    7     40      280
22  2024-06-08  North   mango  tropical   17     40      680
23  2024-06-08  North  orange    citrus   15     20      300
24  2024-06-08  South  orange    citrus   12     20      240
25  2024-06-08  South   mango  tropical   25     40     1000
26  2024-06-09  North  orange    citrus    7     20      140
27  2024-06-09  South   mango  tropical   25     40     1000
28  2024-06-09  South  orange    citrus   11     20      220
29  2024-06-09  South   apple      pome   12     30      360

In [19]:
run("SELECT * FROM sales WHERE fruit LIKE '%an%'")

          date  stall   fruit  category  qty  price  revenue
0   2024-06-03  North   mango  tropical    4     40      160
1   2024-06-03  North  orange    citrus   18     20      360
2   2024-06-03  South  orange    citrus   20     20      400
3   2024-06-04  North  banana  tropical   12     10      120
4   2024-06-04  North   mango  tropical    7     40      280
5   2024-06-04  South  orange    citrus   18     20      360
6   2024-06-05  North   mango  tropical    3     40      120
7   2024-06-05  North  orange    citrus   19     20      380
8   2024-06-05  South   mango  tropical    6     40      240
9   2024-06-05  South  banana  tropical   13     10      130
10  2024-06-05  South  orange    citrus    5     20      100
11  2024-06-06  North  orange    citrus   21     20      420
12  2024-06-06  North   mango  tropical   18     40      720
13  2024-06-06  South   mango  tropical   11     40      440
14  2024-06-06  South  orange    citrus    8     20      160
15  2024-06-07  North   mango  tropical   21     40      840
16  2024-06-07  North  orange    citrus    2     20       40
17  2024-06-07  South  banana  tropical   15     10      150
18  2024-06-07  South  orange    citrus    5     20      100
19  2024-06-07  South   mango  tropical    7     40      280
20  2024-06-08  North   mango  tropical   17     40      680
21  2024-06-08  North  orange    citrus   15     20      300
22  2024-06-08  South  banana  tropical   10     10      100
23  2024-06-08  South  orange    citrus   12     20      240
24  2024-06-08  South   mango  tropical   25     40     1000
25  2024-06-09  North  orange    citrus    7     20      140
26  2024-06-09  North  banana  tropical   21     10      210
27  2024-06-09  South   mango  tropical   25     40     1000
28  2024-06-09  South  orange    citrus   11     20      220
29  2024-06-09  South  banana  tropical   11     10      110

In [20]:
run("SELECT * FROM sales WHERE fruit IN ('apple', 'mango', 'grape')")

          date  stall  fruit  category  qty  price  revenue
0   2024-06-03  North  mango  tropical    4     40      160
1   2024-06-03  North  grape     berry    6     50      300
2   2024-06-03  South  grape     berry   14     50      700
3   2024-06-04  North  apple      pome   15     30      450
4   2024-06-04  North  mango  tropical    7     40      280
5   2024-06-04  North  grape     berry    4     50      200
6   2024-06-04  South  grape     berry   20     50     1000
7   2024-06-04  South  apple      pome    3     30       90
8   2024-06-05  North  mango  tropical    3     40      120
9   2024-06-05  North  grape     berry    5     50      250
10  2024-06-05  North  apple      pome   18     30      540
11  2024-06-05  South  grape     berry   21     50     1050
12  2024-06-05  South  mango  tropical    6     40      240
13  2024-06-06  North  apple      pome   17     30      510
14  2024-06-06  North  mango  tropical   18     40      720
15  2024-06-06  North  grape     berry    4     50      200
16  2024-06-06  South  mango  tropical   11     40      440
17  2024-06-06  South  grape     berry   23     50     1150
18  2024-06-07  North  mango  tropical   21     40      840
19  2024-06-07  North  apple      pome   21     30      630
20  2024-06-07  South  mango  tropical    7     40      280
21  2024-06-07  South  grape     berry    4     50      200
22  2024-06-08  North  mango  tropical   17     40      680
23  2024-06-08  North  grape     berry   15     50      750
24  2024-06-08  South  mango  tropical   25     40     1000
25  2024-06-09  South  mango  tropical   25     40     1000
26  2024-06-09  South  grape     berry   17     50      850
27  2024-06-09  South  apple      pome   12     30      360

In [21]:
run("SELECT * FROM sales WHERE qty BETWEEN 10 AND 20")

          date  stall   fruit  category  qty  price  revenue
0   2024-06-03  North  orange    citrus   18     20      360
1   2024-06-03  South  orange    citrus   20     20      400
2   2024-06-03  South   grape     berry   14     50      700
3   2024-06-04  North   apple      pome   15     30      450
4   2024-06-04  North   lemon    citrus   12     15      180
5   2024-06-04  North  banana  tropical   12     10      120
6   2024-06-04  South   grape     berry   20     50     1000
7   2024-06-04  South  orange    citrus   18     20      360
8   2024-06-04  South   lemon    citrus   10     15      150
9   2024-06-05  North   lemon    citrus   15     15      225
10  2024-06-05  North  orange    citrus   19     20      380
11  2024-06-05  North   apple      pome   18     30      540
12  2024-06-05  South  banana  tropical   13     10      130
13  2024-06-05  South   lemon    citrus   18     15      270
14  2024-06-06  North   apple      pome   17     30      510
15  2024-06-06  North   mango  tropical   18     40      720
16  2024-06-06  South   mango  tropical   11     40      440
17  2024-06-07  South  banana  tropical   15     10      150
18  2024-06-08  North   lemon    citrus   15     15      225
19  2024-06-08  North   mango  tropical   17     40      680
20  2024-06-08  North  orange    citrus   15     20      300
21  2024-06-08  North   grape     berry   15     50      750
22  2024-06-08  South  banana  tropical   10     10      100
23  2024-06-08  South  orange    citrus   12     20      240
24  2024-06-09  South   grape     berry   17     50      850
25  2024-06-09  South  orange    citrus   11     20      220
26  2024-06-09  South  banana  tropical   11     10      110
27  2024-06-09  South   apple      pome   12     30      360

In [22]:
run("SELECT * FROM sales WHERE fruit LIKE 'm%'")

          date  stall  fruit  category  qty  price  revenue
0   2024-06-03  North  mango  tropical    4     40      160
1   2024-06-04  North  mango  tropical    7     40      280
2   2024-06-05  North  mango  tropical    3     40      120
3   2024-06-05  South  mango  tropical    6     40      240
4   2024-06-06  North  mango  tropical   18     40      720
5   2024-06-06  South  mango  tropical   11     40      440
6   2024-06-07  North  mango  tropical   21     40      840
7   2024-06-07  South  mango  tropical    7     40      280
8   2024-06-08  North  mango  tropical   17     40      680
9   2024-06-08  South  mango  tropical   25     40     1000
10  2024-06-09  South  mango  tropical   25     40     1000

In [23]:
#4
run("SELECT fruit, revenue FROM sales ORDER BY revenue DESC")

     fruit  revenue
0    grape     1150
1    grape     1050
2    grape     1000
3    mango     1000
4    mango     1000
5    grape      850
6    mango      840
7    grape      750
8    mango      720
9    grape      700
10   mango      680
11   apple      630
12   apple      540
13   apple      510
14   apple      450
15   mango      440
16  orange      420
17  orange      400
18  orange      380
19  orange      360
20  orange      360
21   apple      360
22   grape      300
23  orange      300
24   mango      280
25   mango      280
26   lemon      270
27   grape      250
28   mango      240
29  orange      240
30   lemon      225
31   lemon      225
32  orange      220
33  banana      210
34   grape      200
35   grape      200
36   grape      200
37   lemon      180
38   mango      160
39  orange      160
40   lemon      150
41  banana      150
42  orange      140
43  banana      130
44  banana      120
45   mango      120
46  banana      110
47  orange      100
48  orange      100
49  banana      100
50   apple       90
51   lemon       75
52   lemon       45
53  orange       40
54   lemon       30

In [24]:
run("SELECT * FROM sales ORDER BY fruit ASC, revenue DESC")

          date  stall   fruit  category  qty  price  revenue
0   2024-06-07  North   apple      pome   21     30      630
1   2024-06-05  North   apple      pome   18     30      540
2   2024-06-06  North   apple      pome   17     30      510
3   2024-06-04  North   apple      pome   15     30      450
4   2024-06-09  South   apple      pome   12     30      360
5   2024-06-04  South   apple      pome    3     30       90
6   2024-06-09  North  banana  tropical   21     10      210
7   2024-06-07  South  banana  tropical   15     10      150
8   2024-06-05  South  banana  tropical   13     10      130
9   2024-06-04  North  banana  tropical   12     10      120
10  2024-06-09  South  banana  tropical   11     10      110
11  2024-06-08  South  banana  tropical   10     10      100
12  2024-06-06  South   grape     berry   23     50     1150
13  2024-06-05  South   grape     berry   21     50     1050
14  2024-06-04  South   grape     berry   20     50     1000
15  2024-06-09  South   grape     berry   17     50      850
16  2024-06-08  North   grape     berry   15     50      750
17  2024-06-03  South   grape     berry   14     50      700
18  2024-06-03  North   grape     berry    6     50      300
19  2024-06-05  North   grape     berry    5     50      250
20  2024-06-04  North   grape     berry    4     50      200
21  2024-06-06  North   grape     berry    4     50      200
22  2024-06-07  South   grape     berry    4     50      200
23  2024-06-05  South   lemon    citrus   18     15      270
24  2024-06-05  North   lemon    citrus   15     15      225
25  2024-06-08  North   lemon    citrus   15     15      225
26  2024-06-04  North   lemon    citrus   12     15      180
27  2024-06-04  South   lemon    citrus   10     15      150
28  2024-06-03  South   lemon    citrus    5     15       75
29  2024-06-09  North   lemon    citrus    3     15       45
30  2024-06-07  South   lemon    citrus    2     15       30
31  2024-06-08  South   mango  tropical   25     40     1000
32  2024-06-09  South   mango  tropical   25     40     1000
33  2024-06-07  North   mango  tropical   21     40      840
34  2024-06-06  North   mango  tropical   18     40      720
35  2024-06-08  North   mango  tropical   17     40      680
36  2024-06-06  South   mango  tropical   11     40      440
37  2024-06-04  North   mango  tropical    7     40      280
38  2024-06-07  South   mango  tropical    7     40      280
39  2024-06-05  South   mango  tropical    6     40      240
40  2024-06-03  North   mango  tropical    4     40      160
41  2024-06-05  North   mango  tropical    3     40      120
42  2024-06-06  North  orange    citrus   21     20      420
43  2024-06-03  South  orange    citrus   20     20      400
44  2024-06-05  North  orange    citrus   19     20      380
45  2024-06-03  North  orange    citrus   18     20      360
46  2024-06-04  South  orange    citrus   18     20      360
47  2024-06-08  North  orange    citrus   15     20      300
48  2024-06-08  South  orange    citrus   12     20      240
49  2024-06-09  South  orange    citrus   11     20      220
50  2024-06-06  South  orange    citrus    8     20      160
51  2024-06-09  North  orange    citrus    7     20      140
52  2024-06-05  South  orange    citrus    5     20      100
53  2024-06-07  South  orange    citrus    5     20      100
54  2024-06-07  North  orange    citrus    2     20       40

In [25]:
run("SELECT * FROM sales ORDER BY revenue DESC")

          date  stall   fruit  category  qty  price  revenue
0   2024-06-06  South   grape     berry   23     50     1150
1   2024-06-05  South   grape     berry   21     50     1050
2   2024-06-04  South   grape     berry   20     50     1000
3   2024-06-08  South   mango  tropical   25     40     1000
4   2024-06-09  South   mango  tropical   25     40     1000
5   2024-06-09  South   grape     berry   17     50      850
6   2024-06-07  North   mango  tropical   21     40      840
7   2024-06-08  North   grape     berry   15     50      750
8   2024-06-06  North   mango  tropical   18     40      720
9   2024-06-03  South   grape     berry   14     50      700
10  2024-06-08  North   mango  tropical   17     40      680
11  2024-06-07  North   apple      pome   21     30      630
12  2024-06-05  North   apple      pome   18     30      540
13  2024-06-06  North   apple      pome   17     30      510
14  2024-06-04  North   apple      pome   15     30      450
15  2024-06-06  South   mango  tropical   11     40      440
16  2024-06-06  North  orange    citrus   21     20      420
17  2024-06-03  South  orange    citrus   20     20      400
18  2024-06-05  North  orange    citrus   19     20      380
19  2024-06-03  North  orange    citrus   18     20      360
20  2024-06-04  South  orange    citrus   18     20      360
21  2024-06-09  South   apple      pome   12     30      360
22  2024-06-03  North   grape     berry    6     50      300
23  2024-06-08  North  orange    citrus   15     20      300
24  2024-06-04  North   mango  tropical    7     40      280
25  2024-06-07  South   mango  tropical    7     40      280
26  2024-06-05  South   lemon    citrus   18     15      270
27  2024-06-05  North   grape     berry    5     50      250
28  2024-06-05  South   mango  tropical    6     40      240
29  2024-06-08  South  orange    citrus   12     20      240
30  2024-06-05  North   lemon    citrus   15     15      225
31  2024-06-08  North   lemon    citrus   15     15      225
32  2024-06-09  South  orange    citrus   11     20      220
33  2024-06-09  North  banana  tropical   21     10      210
34  2024-06-04  North   grape     berry    4     50      200
35  2024-06-06  North   grape     berry    4     50      200
36  2024-06-07  South   grape     berry    4     50      200
37  2024-06-04  North   lemon    citrus   12     15      180
38  2024-06-03  North   mango  tropical    4     40      160
39  2024-06-06  South  orange    citrus    8     20      160
40  2024-06-04  South   lemon    citrus   10     15      150
41  2024-06-07  South  banana  tropical   15     10      150
42  2024-06-09  North  orange    citrus    7     20      140
43  2024-06-05  South  banana  tropical   13     10      130
44  2024-06-04  North  banana  tropical   12     10      120
45  2024-06-05  North   mango  tropical    3     40      120
46  2024-06-09  South  banana  tropical   11     10      110
47  2024-06-05  South  orange    citrus    5     20      100
48  2024-06-07  South  orange    citrus    5     20      100
49  2024-06-08  South  banana  tropical   10     10      100
50  2024-06-04  South   apple      pome    3     30       90
51  2024-06-03  South   lemon    citrus    5     15       75
52  2024-06-09  North   lemon    citrus    3     15       45
53  2024-06-07  North  orange    citrus    2     20       40
54  2024-06-07  South   lemon    citrus    2     15       30

In [26]:
run("SELECT * FROM sales ORDER BY price ASC")

          date  stall   fruit  category  qty  price  revenue
0   2024-06-04  North  banana  tropical   12     10      120
1   2024-06-05  South  banana  tropical   13     10      130
2   2024-06-07  South  banana  tropical   15     10      150
3   2024-06-08  South  banana  tropical   10     10      100
4   2024-06-09  North  banana  tropical   21     10      210
5   2024-06-09  South  banana  tropical   11     10      110
6   2024-06-03  South   lemon    citrus    5     15       75
7   2024-06-04  North   lemon    citrus   12     15      180
8   2024-06-04  South   lemon    citrus   10     15      150
9   2024-06-05  North   lemon    citrus   15     15      225
10  2024-06-05  South   lemon    citrus   18     15      270
11  2024-06-07  South   lemon    citrus    2     15       30
12  2024-06-08  North   lemon    citrus   15     15      225
13  2024-06-09  North   lemon    citrus    3     15       45
14  2024-06-03  North  orange    citrus   18     20      360
15  2024-06-03  South  orange    citrus   20     20      400
16  2024-06-04  South  orange    citrus   18     20      360
17  2024-06-05  North  orange    citrus   19     20      380
18  2024-06-05  South  orange    citrus    5     20      100
19  2024-06-06  North  orange    citrus   21     20      420
20  2024-06-06  South  orange    citrus    8     20      160
21  2024-06-07  North  orange    citrus    2     20       40
22  2024-06-07  South  orange    citrus    5     20      100
23  2024-06-08  North  orange    citrus   15     20      300
24  2024-06-08  South  orange    citrus   12     20      240
25  2024-06-09  North  orange    citrus    7     20      140
26  2024-06-09  South  orange    citrus   11     20      220
27  2024-06-04  North   apple      pome   15     30      450
28  2024-06-04  South   apple      pome    3     30       90
29  2024-06-05  North   apple      pome   18     30      540
30  2024-06-06  North   apple      pome   17     30      510
31  2024-06-07  North   apple      pome   21     30      630
32  2024-06-09  South   apple      pome   12     30      360
33  2024-06-03  North   mango  tropical    4     40      160
34  2024-06-04  North   mango  tropical    7     40      280
35  2024-06-05  North   mango  tropical    3     40      120
36  2024-06-05  South   mango  tropical    6     40      240
37  2024-06-06  North   mango  tropical   18     40      720
38  2024-06-06  South   mango  tropical   11     40      440
39  2024-06-07  North   mango  tropical   21     40      840
40  2024-06-07  South   mango  tropical    7     40      280
41  2024-06-08  North   mango  tropical   17     40      680
42  2024-06-08  South   mango  tropical   25     40     1000
43  2024-06-09  South   mango  tropical   25     40     1000
44  2024-06-03  North   grape     berry    6     50      300
45  2024-06-03  South   grape     berry   14     50      700
46  2024-06-04  North   grape     berry    4     50      200
47  2024-06-04  South   grape     berry   20     50     1000
48  2024-06-05  North   grape     berry    5     50      250
49  2024-06-05  South   grape     berry   21     50     1050
50  2024-06-06  North   grape     berry    4     50      200
51  2024-06-06  South   grape     berry   23     50     1150
52  2024-06-07  South   grape     berry    4     50      200
53  2024-06-08  North   grape     berry   15     50      750
54  2024-06-09  South   grape     berry   17     50      850

In [27]:
run("SELECT * FROM sales ORDER BY fruit ASC, revenue DESC")

          date  stall   fruit  category  qty  price  revenue
0   2024-06-07  North   apple      pome   21     30      630
1   2024-06-05  North   apple      pome   18     30      540
2   2024-06-06  North   apple      pome   17     30      510
3   2024-06-04  North   apple      pome   15     30      450
4   2024-06-09  South   apple      pome   12     30      360
5   2024-06-04  South   apple      pome    3     30       90
6   2024-06-09  North  banana  tropical   21     10      210
7   2024-06-07  South  banana  tropical   15     10      150
8   2024-06-05  South  banana  tropical   13     10      130
9   2024-06-04  North  banana  tropical   12     10      120
10  2024-06-09  South  banana  tropical   11     10      110
11  2024-06-08  South  banana  tropical   10     10      100
12  2024-06-06  South   grape     berry   23     50     1150
13  2024-06-05  South   grape     berry   21     50     1050
14  2024-06-04  South   grape     berry   20     50     1000
15  2024-06-09  South   grape     berry   17     50      850
16  2024-06-08  North   grape     berry   15     50      750
17  2024-06-03  South   grape     berry   14     50      700
18  2024-06-03  North   grape     berry    6     50      300
19  2024-06-05  North   grape     berry    5     50      250
20  2024-06-04  North   grape     berry    4     50      200
21  2024-06-06  North   grape     berry    4     50      200
22  2024-06-07  South   grape     berry    4     50      200
23  2024-06-05  South   lemon    citrus   18     15      270
24  2024-06-05  North   lemon    citrus   15     15      225
25  2024-06-08  North   lemon    citrus   15     15      225
26  2024-06-04  North   lemon    citrus   12     15      180
27  2024-06-04  South   lemon    citrus   10     15      150
28  2024-06-03  South   lemon    citrus    5     15       75
29  2024-06-09  North   lemon    citrus    3     15       45
30  2024-06-07  South   lemon    citrus    2     15       30
31  2024-06-08  South   mango  tropical   25     40     1000
32  2024-06-09  South   mango  tropical   25     40     1000
33  2024-06-07  North   mango  tropical   21     40      840
34  2024-06-06  North   mango  tropical   18     40      720
35  2024-06-08  North   mango  tropical   17     40      680
36  2024-06-06  South   mango  tropical   11     40      440
37  2024-06-04  North   mango  tropical    7     40      280
38  2024-06-07  South   mango  tropical    7     40      280
39  2024-06-05  South   mango  tropical    6     40      240
40  2024-06-03  North   mango  tropical    4     40      160
41  2024-06-05  North   mango  tropical    3     40      120
42  2024-06-06  North  orange    citrus   21     20      420
43  2024-06-03  South  orange    citrus   20     20      400
44  2024-06-05  North  orange    citrus   19     20      380
45  2024-06-03  North  orange    citrus   18     20      360
46  2024-06-04  South  orange    citrus   18     20      360
47  2024-06-08  North  orange    citrus   15     20      300
48  2024-06-08  South  orange    citrus   12     20      240
49  2024-06-09  South  orange    citrus   11     20      220
50  2024-06-06  South  orange    citrus    8     20      160
51  2024-06-09  North  orange    citrus    7     20      140
52  2024-06-05  South  orange    citrus    5     20      100
53  2024-06-07  South  orange    citrus    5     20      100
54  2024-06-07  North  orange    citrus    2     20       40

In [28]:
#5
run("SELECT fruit, revenue FROM sales ORDER BY revenue DESC LIMIT 5")

   fruit  revenue
0  grape     1150
1  grape     1050
2  grape     1000
3  mango     1000
4  mango     1000

In [29]:
run("SELECT * FROM sales ORDER BY revenue DESC LIMIT 3")

         date  stall  fruit category  qty  price  revenue
0  2024-06-06  South  grape    berry   23     50     1150
1  2024-06-05  South  grape    berry   21     50     1050
2  2024-06-04  South  grape    berry   20     50     1000

In [30]:
run("SELECT * FROM sales ORDER BY revenue ASC LIMIT 5")

         date  stall   fruit category  qty  price  revenue
0  2024-06-07  South   lemon   citrus    2     15       30
1  2024-06-07  North  orange   citrus    2     20       40
2  2024-06-09  North   lemon   citrus    3     15       45
3  2024-06-03  South   lemon   citrus    5     15       75
4  2024-06-04  South   apple     pome    3     30       90

In [31]:
#6
run("SELECT DISTINCT fruit FROM sales")

    fruit
0   mango
1  orange
2   grape
3   lemon
4   apple
5  banana

In [32]:
run("SELECT DISTINCT stall FROM sales")

   stall
0  North
1  South

In [33]:
run("SELECT DISTINCT category FROM sales")

   category
0  tropical
1    citrus
2     berry
3      pome

In [34]:
run("SELECT DISTINCT price FROM sales ORDER BY price ASC")

   price
0     10
1     15
2     20
3     30
4     40
5     50

In [35]:
#7
run("""
    SELECT fruit, qty, price,
           qty * price AS revenue
    FROM sales
    WHERE qty * price > 300
""")

     fruit  qty  price  revenue
0   orange   18     20      360
1   orange   20     20      400
2    grape   14     50      700
3    apple   15     30      450
4    grape   20     50     1000
5   orange   18     20      360
6   orange   19     20      380
7    apple   18     30      540
8    grape   21     50     1050
9   orange   21     20      420
10   apple   17     30      510
11   mango   18     40      720
12   mango   11     40      440
13   grape   23     50     1150
14   mango   21     40      840
15   apple   21     30      630
16   mango   17     40      680
17   grape   15     50      750
18   mango   25     40     1000
19   mango   25     40     1000
20   grape   17     50      850
21   apple   12     30      360

In [36]:
run("""
    SELECT fruit, qty, price,
           qty * price AS revenue
    FROM sales
    WHERE qty * price > 300
""")

     fruit  qty  price  revenue
0   orange   18     20      360
1   orange   20     20      400
2    grape   14     50      700
3    apple   15     30      450
4    grape   20     50     1000
5   orange   18     20      360
6   orange   19     20      380
7    apple   18     30      540
8    grape   21     50     1050
9   orange   21     20      420
10   apple   17     30      510
11   mango   18     40      720
12   mango   11     40      440
13   grape   23     50     1150
14   mango   21     40      840
15   apple   21     30      630
16   mango   17     40      680
17   grape   15     50      750
18   mango   25     40     1000
19   mango   25     40     1000
20   grape   17     50      850
21   apple   12     30      360

In [37]:
run("""
    SELECT fruit,
           qty * 2 AS double_qty
    FROM sales
""")

     fruit  double_qty
0    mango           8
1   orange          36
2    grape          12
3   orange          40
4    grape          28
5    lemon          10
6    apple          30
7    lemon          24
8   banana          24
9    mango          14
10   grape           8
11   grape          40
12  orange          36
13   lemon          20
14   apple           6
15   mango           6
16   lemon          30
17   grape          10
18  orange          38
19   apple          36
20   grape          42
21   mango          12
22  banana          26
23  orange          10
24   lemon          36
25  orange          42
26   apple          34
27   mango          36
28   grape           8
29   mango          22
30   grape          46
31  orange          16
32   mango          42
33  orange           4
34   apple          42
35  banana          30
36   lemon           4
37  orange          10
38   mango          14
39   grape           8
40   lemon          30
41   mango          34
42  orange          30
43   grape          30
44  banana          20
45  orange          24
46   mango          50
47  orange          14
48  banana          42
49   lemon           6
50   mango          50
51   grape          34
52  orange          22
53  banana          22
54   apple          24

In [38]:
#8
demo = pd.DataFrame({
    "fruit": ["apple", "banana", "cherry"],
    "supplier": ["A", None, "C"]
})

demo.to_sql("demo", conn, if_exists="replace", index=False)

3

In [39]:
run("SELECT * FROM demo WHERE supplier IS NULL")

    fruit supplier
0  banana     None

In [40]:
run("SELECT * FROM demo WHERE supplier IS NOT NULL")

    fruit supplier
0   apple        A
1  cherry        C

In [41]:
run("SELECT * FROM demo WHERE supplier IS NULL")

    fruit supplier
0  banana     None

In [42]:
run("SELECT * FROM demo WHERE supplier IS NOT NULL")

    fruit supplier
0   apple        A
1  cherry        C

In [43]:
#endofdaybuild

In [44]:

# Q1: Every distinct fruit sold
run("SELECT DISTINCT fruit FROM sales")

    fruit
0   mango
1  orange
2   grape
3   lemon
4   apple
5  banana

In [45]:
# Q2: All sales at the North stall over ₹300 revenue, biggest first
run("""
SELECT *,
       qty * price AS revenue
FROM sales
WHERE stall = 'North'
  AND qty * price > 300
ORDER BY revenue DESC
""")

          date  stall   fruit  category  qty  price  revenue  revenue
0   2024-06-07  North   mango  tropical   21     40      840      840
1   2024-06-08  North   grape     berry   15     50      750      750
2   2024-06-06  North   mango  tropical   18     40      720      720
3   2024-06-08  North   mango  tropical   17     40      680      680
4   2024-06-07  North   apple      pome   21     30      630      630
5   2024-06-05  North   apple      pome   18     30      540      540
6   2024-06-06  North   apple      pome   17     30      510      510
7   2024-06-04  North   apple      pome   15     30      450      450
8   2024-06-06  North  orange    citrus   21     20      420      420
9   2024-06-05  North  orange    citrus   19     20      380      380
10  2024-06-03  North  orange    citrus   18     20      360      360

In [46]:
# Q3: The 5 biggest single sales of the week
run("""
SELECT *,
       qty * price AS revenue
FROM sales
ORDER BY revenue DESC
LIMIT 5
""")

         date  stall  fruit  category  qty  price  revenue  revenue
0  2024-06-06  South  grape     berry   23     50     1150     1150
1  2024-06-05  South  grape     berry   21     50     1050     1050
2  2024-06-04  South  grape     berry   20     50     1000     1000
3  2024-06-08  South  mango  tropical   25     40     1000     1000
4  2024-06-09  South  mango  tropical   25     40     1000     1000

In [47]:
# Q4: All grape and mango sales priced ₹40 or more
run("""
SELECT *
FROM sales
WHERE fruit IN ('grape', 'mango')
  AND price >= 40
""")

          date  stall  fruit  category  qty  price  revenue
0   2024-06-03  North  mango  tropical    4     40      160
1   2024-06-03  North  grape     berry    6     50      300
2   2024-06-03  South  grape     berry   14     50      700
3   2024-06-04  North  mango  tropical    7     40      280
4   2024-06-04  North  grape     berry    4     50      200
5   2024-06-04  South  grape     berry   20     50     1000
6   2024-06-05  North  mango  tropical    3     40      120
7   2024-06-05  North  grape     berry    5     50      250
8   2024-06-05  South  grape     berry   21     50     1050
9   2024-06-05  South  mango  tropical    6     40      240
10  2024-06-06  North  mango  tropical   18     40      720
11  2024-06-06  North  grape     berry    4     50      200
12  2024-06-06  South  mango  tropical   11     40      440
13  2024-06-06  South  grape     berry   23     50     1150
14  2024-06-07  North  mango  tropical   21     40      840
15  2024-06-07  South  mango  tropical    7     40      280
16  2024-06-07  South  grape     berry    4     50      200
17  2024-06-08  North  mango  tropical   17     40      680
18  2024-06-08  North  grape     berry   15     50      750
19  2024-06-08  South  mango  tropical   25     40     1000
20  2024-06-09  South  mango  tropical   25     40     1000
21  2024-06-09  South  grape     berry   17     50      850

In [48]:
# Q5: All sales of fruits whose name contains "an"
run("""
SELECT *
FROM sales
WHERE fruit LIKE '%an%'
""")

          date  stall   fruit  category  qty  price  revenue
0   2024-06-03  North   mango  tropical    4     40      160
1   2024-06-03  North  orange    citrus   18     20      360
2   2024-06-03  South  orange    citrus   20     20      400
3   2024-06-04  North  banana  tropical   12     10      120
4   2024-06-04  North   mango  tropical    7     40      280
5   2024-06-04  South  orange    citrus   18     20      360
6   2024-06-05  North   mango  tropical    3     40      120
7   2024-06-05  North  orange    citrus   19     20      380
8   2024-06-05  South   mango  tropical    6     40      240
9   2024-06-05  South  banana  tropical   13     10      130
10  2024-06-05  South  orange    citrus    5     20      100
11  2024-06-06  North  orange    citrus   21     20      420
12  2024-06-06  North   mango  tropical   18     40      720
13  2024-06-06  South   mango  tropical   11     40      440
14  2024-06-06  South  orange    citrus    8     20      160
15  2024-06-07  North   mango  tropical   21     40      840
16  2024-06-07  North  orange    citrus    2     20       40
17  2024-06-07  South  banana  tropical   15     10      150
18  2024-06-07  South  orange    citrus    5     20      100
19  2024-06-07  South   mango  tropical    7     40      280
20  2024-06-08  North   mango  tropical   17     40      680
21  2024-06-08  North  orange    citrus   15     20      300
22  2024-06-08  South  banana  tropical   10     10      100
23  2024-06-08  South  orange    citrus   12     20      240
24  2024-06-08  South   mango  tropical   25     40     1000
25  2024-06-09  North  orange    citrus    7     20      140
26  2024-06-09  North  banana  tropical   21     10      210
27  2024-06-09  South   mango  tropical   25     40     1000
28  2024-06-09  South  orange    citrus   11     20      220
29  2024-06-09  South  banana  tropical   11     10      110

In [49]:
# Q6: All sales with qty between 10 and 20, sorted by revenue
run("""
SELECT *,
       qty * price AS revenue
FROM sales
WHERE qty BETWEEN 10 AND 20
ORDER BY revenue DESC
""")

          date  stall   fruit  category  qty  price  revenue  revenue
0   2024-06-04  South   grape     berry   20     50     1000     1000
1   2024-06-09  South   grape     berry   17     50      850      850
2   2024-06-08  North   grape     berry   15     50      750      750
3   2024-06-06  North   mango  tropical   18     40      720      720
4   2024-06-03  South   grape     berry   14     50      700      700
5   2024-06-08  North   mango  tropical   17     40      680      680
6   2024-06-05  North   apple      pome   18     30      540      540
7   2024-06-06  North   apple      pome   17     30      510      510
8   2024-06-04  North   apple      pome   15     30      450      450
9   2024-06-06  South   mango  tropical   11     40      440      440
10  2024-06-03  South  orange    citrus   20     20      400      400
11  2024-06-05  North  orange    citrus   19     20      380      380
12  2024-06-03  North  orange    citrus   18     20      360      360
13  2024-06-04  South  orange    citrus   18     20      360      360
14  2024-06-09  South   apple      pome   12     30      360      360
15  2024-06-08  North  orange    citrus   15     20      300      300
16  2024-06-05  South   lemon    citrus   18     15      270      270
17  2024-06-08  South  orange    citrus   12     20      240      240
18  2024-06-05  North   lemon    citrus   15     15      225      225
19  2024-06-08  North   lemon    citrus   15     15      225      225
20  2024-06-09  South  orange    citrus   11     20      220      220
21  2024-06-04  North   lemon    citrus   12     15      180      180
22  2024-06-04  South   lemon    citrus   10     15      150      150
23  2024-06-07  South  banana  tropical   15     10      150      150
24  2024-06-05  South  banana  tropical   13     10      130      130
25  2024-06-04  North  banana  tropical   12     10      120      120
26  2024-06-09  South  banana  tropical   11     10      110      110
27  2024-06-08  South  banana  tropical   10     10      100      100

In [50]:
# Q7: Every fruit with a price of ₹30 or more, listed once each
run("""
SELECT DISTINCT fruit
FROM sales
WHERE price >= 30
""")

   fruit
0  mango
1  grape
2  apple

In [51]:
#strech

In [52]:
# Stretch (a): Label each sale as premium or regular
run("""
SELECT fruit,
       price,
       CASE
           WHEN price >= 40 THEN 'premium'
           ELSE 'regular'
       END AS tier
FROM sales
""")

     fruit  price     tier
0    mango     40  premium
1   orange     20  regular
2    grape     50  premium
3   orange     20  regular
4    grape     50  premium
5    lemon     15  regular
6    apple     30  regular
7    lemon     15  regular
8   banana     10  regular
9    mango     40  premium
10   grape     50  premium
11   grape     50  premium
12  orange     20  regular
13   lemon     15  regular
14   apple     30  regular
15   mango     40  premium
16   lemon     15  regular
17   grape     50  premium
18  orange     20  regular
19   apple     30  regular
20   grape     50  premium
21   mango     40  premium
22  banana     10  regular
23  orange     20  regular
24   lemon     15  regular
25  orange     20  regular
26   apple     30  regular
27   mango     40  premium
28   grape     50  premium
29   mango     40  premium
30   grape     50  premium
31  orange     20  regular
32   mango     40  premium
33  orange     20  regular
34   apple     30  regular
35  banana     10  regular
36   lemon     15  regular
37  orange     20  regular
38   mango     40  premium
39   grape     50  premium
40   lemon     15  regular
41   mango     40  premium
42  orange     20  regular
43   grape     50  premium
44  banana     10  regular
45  orange     20  regular
46   mango     40  premium
47  orange     20  regular
48  banana     10  regular
49   lemon     15  regular
50   mango     40  premium
51   grape     50  premium
52  orange     20  regular
53  banana     10  regular
54   apple     30  regular

In [53]:
# Stretch (b): Fruits with exactly 5 letters
run("""
SELECT *
FROM sales
WHERE LENGTH(fruit) = 5
""")

          date  stall  fruit  category  qty  price  revenue
0   2024-06-03  North  mango  tropical    4     40      160
1   2024-06-03  North  grape     berry    6     50      300
2   2024-06-03  South  grape     berry   14     50      700
3   2024-06-03  South  lemon    citrus    5     15       75
4   2024-06-04  North  apple      pome   15     30      450
5   2024-06-04  North  lemon    citrus   12     15      180
6   2024-06-04  North  mango  tropical    7     40      280
7   2024-06-04  North  grape     berry    4     50      200
8   2024-06-04  South  grape     berry   20     50     1000
9   2024-06-04  South  lemon    citrus   10     15      150
10  2024-06-04  South  apple      pome    3     30       90
11  2024-06-05  North  mango  tropical    3     40      120
12  2024-06-05  North  lemon    citrus   15     15      225
13  2024-06-05  North  grape     berry    5     50      250
14  2024-06-05  North  apple      pome   18     30      540
15  2024-06-05  South  grape     berry   21     50     1050
16  2024-06-05  South  mango  tropical    6     40      240
17  2024-06-05  South  lemon    citrus   18     15      270
18  2024-06-06  North  apple      pome   17     30      510
19  2024-06-06  North  mango  tropical   18     40      720
20  2024-06-06  North  grape     berry    4     50      200
21  2024-06-06  South  mango  tropical   11     40      440
22  2024-06-06  South  grape     berry   23     50     1150
23  2024-06-07  North  mango  tropical   21     40      840
24  2024-06-07  North  apple      pome   21     30      630
25  2024-06-07  South  lemon    citrus    2     15       30
26  2024-06-07  South  mango  tropical    7     40      280
27  2024-06-07  South  grape     berry    4     50      200
28  2024-06-08  North  lemon    citrus   15     15      225
29  2024-06-08  North  mango  tropical   17     40      680
30  2024-06-08  North  grape     berry   15     50      750
31  2024-06-08  South  mango  tropical   25     40     1000
32  2024-06-09  North  lemon    citrus    3     15       45
33  2024-06-09  South  mango  tropical   25     40     1000
34  2024-06-09  South  grape     berry   17     50      850
35  2024-06-09  South  apple      pome   12     30      360

In [54]:
# Stretch (c): Premium fruits at North or any grape
run("""
SELECT *
FROM sales
WHERE (price >= 40 AND stall = 'North')
   OR fruit = 'grape'
""")

          date  stall  fruit  category  qty  price  revenue
0   2024-06-03  North  mango  tropical    4     40      160
1   2024-06-03  North  grape     berry    6     50      300
2   2024-06-03  South  grape     berry   14     50      700
3   2024-06-04  North  mango  tropical    7     40      280
4   2024-06-04  North  grape     berry    4     50      200
5   2024-06-04  South  grape     berry   20     50     1000
6   2024-06-05  North  mango  tropical    3     40      120
7   2024-06-05  North  grape     berry    5     50      250
8   2024-06-05  South  grape     berry   21     50     1050
9   2024-06-06  North  mango  tropical   18     40      720
10  2024-06-06  North  grape     berry    4     50      200
11  2024-06-06  South  grape     berry   23     50     1150
12  2024-06-07  North  mango  tropical   21     40      840
13  2024-06-07  South  grape     berry    4     50      200
14  2024-06-08  North  mango  tropical   17     40      680
15  2024-06-08  North  grape     berry   15     50      750
16  2024-06-09  South  grape     berry   17     50      850

In [55]:
# Stretch (d): Load fruits.csv into a second table
fruits = pd.read_csv("fruits.csv")
fruits.to_sql("fruits", conn, if_exists="replace", index=False)

6

In [56]:
# Display the fruits table
run("SELECT * FROM fruits")

    fruit    supplier  cost_price    origin
0   apple  FreshFarms          18     local
1  banana  TropicoLtd           6  imported
2  orange    CitrusCo          12     local
3   mango  TropicoLtd          25  imported
4   grape   VineyardX          32  imported
5    pear   OrchardCo          20     local